#----------------DEV Environment----------------
# [Server]
server:
#  address: 127.0.0.1
  port: 8080 # 服务绑定的端口，不写默认是8080
  servlet:
    context-path: / # 服务的路径，不写默认为空
  tomcat:
    max-threads: 100
    uri-encoding: UTF-8

# [Spring]
spring:
  application:
    # 应用名称
    name: Global Region

#  profiles:
#    active: prod
  redis:
    #数据库索引
    database: 0
    host: local.redis.my
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
    timeout: 10000

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  messages:
    basename: i18n/messages/messages
    encoding: UTF-8
    fallbackToSystemLocale: false

#  datasource:
#    #  驱动
#    driver-class-name: org.h2.Driver
#    # h2 内存数据库 内存模式连接配置 库名: area
#    url: jdbc:h2:mem:area
#    # 初始化数据表 DDL
#    schema: classpath:/schema.sql
#    #  初始化数据 DML
#    data: classpath:/data.sql
#    username: sa
#    password: sa

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.79.49:3306/middle_school
    username: root
    password: ayongAli.,123
  h2:
    #    开启console 访问 默认false
    console:
      enabled: true
      settings:
        #      开启h2 console 跟踪 方便调试  默认 false
        trace: true
        #      允许console 远程访问 默认false
        web-allow-others: true
      #  h2 访问路径上下文
      path: /h2-console

# [Mybatis]
#mybatis:
#  mapper-locations: classpath*:/com/littlefox/**/mysql/*.xml
#  type-aliases-package: com.littlefox.**.model


# [Mybatis]
#mybatis:
#  mapper-locations: classpath*:/mapping/*.xml
#  type-aliases-package: com.mexue.middle.school.entity

# mybatis.mapper-locations 配置多个mapper路径

logging:
  level:
    com:
      mexue:
        middle:
          school: debug
#  logging.level.root=INFO
#  logging.level.com.mexue.middle.school=DEBUG
mybatis:
  mapper-locations: classpath*:/mapping/*.xml,classpath*:/com/littlefox/**/mysql/*.xml


girl:
  cupSize: A
  age: 10