spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 123123
server:
    port: 8003

girl:
    cupSize: B
    age: 18